export const SampleProduct: Product[] = [
    {
    name: 'Nike Hoodie',
    slug: 'Hoodie',
    image: '../client/public/images/nikehoodie.png',
    category: 'Hoodie',
    brand: 'Nike',
    price: 39.99,
    CountInStock: 4,
    Description: 'Hoodie',
    Rating: 4,
    NumReviews: 0,
    },
    {
    name: 'Adidas Hoodie',
    slug: 'Hoodie',
    image: '../client/public/images/adidashoodie.png',
    category: 'Hoodie',
    brand: 'Adidas',
    price: 39.99,
    CountInStock: 4,
    Description: 'Hoodie',
    Rating: 4,
    NumReviews: 0,
    },
    {
    name: 'Puma Hoodie',
    slug: 'Hoodie',
    image: '../client/public/images/pumahoodie.jpg',
    category: 'Hoodie',
    brand: 'Puma',
    price: 39.99,
    CountInStock: 4,
    Description: 'Hoodie',
    Rating: 4,
    NumReviews: 0,
    },
];